# Publish a build for development. The Xcode framework is debuggable.
name: KMMBridge-Debug
on:
  workflow_dispatch:

jobs:
  call-publish:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/Base-Publish.yml
    with:
      build-debug: true