# Publish a build for development. The Xcode framework is debuggable.
name: KMMBridge-Debug
on:
  workflow_dispatch:

jobs:
  call-publish:
    uses: ./.github/workflows/Base-Publish.yml
    with:
      build-debug: true